language: python
sudo: false

virtualenv:
  system_site_packages: false

cache:
  directories:
    - $HOME/.cache/pip
#    - $HOME/hdf5-1.10.0-patch1-linux-centos7-x86_64-gcc485-shared
#    - $HOME/hdf5-1.8.19-linux-centos7-x86_64-gcc485-shared
    - $HOME/hdf5-1.8.20-linux-centos7-x86_64-gcc485-shared
    - $HOME/nfft-3.2.3
    - $HOME/libspimage
    - $HOME/spsim
    - $HOME/local
    - $HOME/localpy
    - $HOME/virutalenv

matrix:
  include:
    - python: '2.7'
#    - python: '3.4'
#    - python: '3.5'
#    - python: '3.6'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - kubuntu-backports
      - couchbase-precise
    packages:
      - libpng-dev
      - libtiff4-dev
      - libfftw3-dev
      - cmake
      - gsl-bin
      - libgsl0-dev
      - swig

before_install:
  - echo $HOME
  - export PY_SITE=$(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
  - export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${HOME}/local/lib:${HOME}/local/lib64:${PY27_PREFIX}/lib
  - export PYTHONPATH=${HOME}/localpy:${PYTHONPATH}
# Install hdf5
  - cd $HOME
#  - if [ ! -d "$HOME/hdf5-1.10.0-patch1-linux-centos7-x86_64-gcc485-shared/include" ]; then wget https://support.hdfgroup.org/ftp/HDF5/current/bin/linux-centos7-x86_64-gcc485/hdf5-1.10.0-patch1-linux-centos7-x86_64-gcc485-shared.tar.gz && tar xvzf hdf5-1.10.0-patch1-linux-centos7-x86_64-gcc485-shared.tar.gz; else echo 'Using hdf5 from cached directory'; fi
  # - export HDF5_DIR=${HOME}/hdf5-1.8.19-linux-centos7-x86_64-gcc485-shared/
  # - if [ ! -d "${HDF5_DIR}/include" ]; then wget https://support.hdfgroup.org/ftp/HDF5/current18/bin/linux-centos7-x86_64-gcc485/hdf5-1.8.19-linux-centos7-x86_64-gcc485-shared.tar.gz && tar xvzf hdf5-1.8.19-linux-centos7-x86_64-gcc485-shared.tar.gz; else echo 'Using hdf5 from cached directory'; fi
  - export HDF5_DIR=${HOME}/hdf5-1.8.20-linux-centos7-x86_64-gcc485-shared/
  - if [ ! -d "${HDF5_DIR}/include" ]; then wget https://support.hdfgroup.org/ftp/HDF5/current18/bin/hdf5-1.8.20-linux-centos7-x86_64-gcc485-shared.tar.gz && tar xvzf hdf5-1.8.20-linux-centos7-x86_64-gcc485-shared.tar.gz; else echo 'Using hdf5 from cached directory'; fi
  
#  - export LD_LIBRARY_PATH=${HOME}/hdf5-1.10.0-patch1-linux-centos7-x86_64-gcc485-shared/lib:${LD_LIBRARY_PATH}
  - export LD_LIBRARY_PATH=${HDF5_DIR}/lib:${LD_LIBRARY_PATH}
  - ls ${HOME}/
  - ls ${HDF5_DIR}
  - ls ${HDF5_DIR}/include
  - ls ${HDF5_DIR}/lib
# Install numpy and scipy
  - pip install numpy
  - pip install scipy
# Install configparser with pip (this is to make condor compatible with Python 3, which no longer has the ConfigParser module)
  - pip install configparser
# Install h5py (we want an h5py that is built with the new hdf5 version, that is why)
#  - export HDF5_DIR=${HOME}/hdf5-1.10.0-patch1-linux-centos7-x86_64-gcc485-shared/
#  - export HDF5_DIR=${HOME}/hdf5-1.8.19-linux-centos7-x86_64-gcc485-shared/
  - export HDF5_DIR=${HOME}/hdf5-1.8.20-linux-centos7-x86_64-gcc485-shared/
  - pip install h5py
# Testing imports
  - python -c "import numpy; print(numpy.__file__)"
  - python -c "import scipy; print(scipy.__file__)"
  - python -c "import h5py; print(h5py.__file__)"
# Install libspimage
  - cd $HOME
  - if [ ! -d "$HOME/libspimage/.git" ]; then git clone https://github.com/FilipeMaia/libspimage; else echo 'Using libspimage from cached directory'; fi
  - mkdir -p libspimage/build && cd libspimage/build
  - git pull
  - cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DUSE_CUDA=OFF -DPYTHON_WRAPPERS=ON -DHDF5_INCLUDE_DIR=${HDF5_DIR}/include -DHDF5_LIBRARY=${HDF5_DIR}/lib/libhdf5.so -DCMAKE_INSTALL_PREFIX=${HOME}/virtualenv/python${TRAVIS_PYTHON_VERSION} -DPYTHON_INSTDIR=${PY_SITE} ..
  - make
  #; -j 2 VERBOSE=1
  - make install
# Install NFFT
  - cd $HOME
  - if [ ! -d "$HOME/nfft-3.2.3/include" ]; then wget https://www-user.tu-chemnitz.de/~potts/nfft/download/nfft-3.2.3.tar.gz && tar xvzf nfft-3.2.3.tar.gz; cd nfft-3.2.3 && ./configure --prefix=${HOME}/local && make && make install; else echo 'Using NFFT from cached directory'; fi
# Install spsim
  - cd $HOME
  - if [ ! -d "$HOME/spsim/.git" ]; then git clone https://github.com/FilipeMaia/spsim; else echo 'Using spsim from cached directory'; fi
  - mkdir -p spsim/build && cd spsim/build
  - git pull
  - cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DBUILD_LIBRARY=ON -DUSE_CUDA=OFF -DUSE_NFFT=OFF -DPYTHON_WRAPPERS=ON -DHDF5_INCLUDE_DIR=${HDF5_DIR}/include -DHDF5_LIBRARY=${HDF5_DIR}/lib/libhdf5.so -DCMAKE_INSTALL_PREFIX=${HOME}/virtualenv/python${TRAVIS_PYTHON_VERSION} -DPYTHON_INSTDIR=${PY_SITE}  ..
  - make VERBOSE=1
  - make install
  - ls -alh $HOME/local/lib
# Command to install dependencies
install:
# Install condor
  - cd $HOME
  - git clone https://github.com/FXIhub/condor.git
  - cd condor
  - python setup.py install --nfft-include-dir=$HOME/local/include --nfft-library-dir=$HOME/local/lib
# command to run tests
script:
  - echo $LD_LIBRARY_PATH
  - echo $PYTHONPATH
  # TESTING IMPORTS
  - python -c "import spimage; print(spimage.__file__)"
  - python -c "import spsim; print(spsim.__file__)"
  - python -c "import spimage_pybackend; print(spimage_pybackend.__file__)"
  - python -c "import spsim_pybackend; print(spsim_pybackend.__file__)"
  - python -c "import condor; print(condor.__file__)"
  # UNITTESTS
  - python -m unittest -v condor.tests.test_all

#  - cd $HOME
#  - pip install -e .
#  - mkdir $HOME/dependencies
#  - cd $HOME/dependencies
#  - git clone https://gitlab.mpcdf.mpg.de/nomad-lab/python-common.git
#  - cd python-common
#  - pip install -r requirements.txt
#  - pip install -e .
#  - cd ../
#
#  - python --version
#  - pip freeze
#  - pip install pyflakes
#  - cd $CI_PROJECT_DIR
#  - nosetests -v --nocapture --logging-level=INFO --cover-package=ai4materials --with-coverage
#  - pyflakes ai4materials

